name: ibp_app_ver2
description: "A new Flutter project."
publish_to: "none" # This line prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.4.6
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.1.0
  smooth_page_indicator: ^1.1.0
  firebase_core: ^2.10.0 # Adjusted to a compatible version
  firebase_auth: ^4.5.0 # Adjusted to a compatible version
  cloud_firestore: ^4.5.0 # Adjusted to a compatible version
  provider: ^6.0.0
  image_picker: ^0.8.4+3
  mime: ^1.0.0
  image: ^3.0.1
  image_picker_for_web: ^2.1.7
  html: ^0.15.0
  universal_html: ^2.0.7
  firebase_storage: ^11.0.0
  http: ^0.13.4
  intl: ^0.18.1
  qr_flutter: ^4.0.0
  path_provider: ^2.0.11
  cached_network_image: ^3.0.0
  qr_code_scanner: ^1.0.1
  recase: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/ibp_splash_screen.mp4 # Video asset declared here

